project:
  type: book

book:
  title: "Music_meta_book"
  author: "Santiago Ortega"
  date: last-modified
  chapters:
    - index.qmd
    - lnRR.qmd
    - overall_effect.qmd
    - uni_moderators.qmd
    - multi_moderator.qmd
    - publication_bias.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: litera
      dark: darkly
    mainfont: "Atkinson Hyperlegible"
    code-tools: true
    toc: true
    toc-depth: 3
    toc-location: left

execute:
  freeze: auto # Automatically caches results to speed up rendering
  warning: false
  message: false

editor: visual

