project:
  type: book
  output-dir: ../docsoutput-dir: ../docs

book:
  title: "Music_meta_book"
  author: "TBA"
  date: last-modified
  chapters:
    - index.qmd
    - lnRR.qmd
    - overall_effect.qmd
    - uni_moderators.qmd
    - multi_moderator.qmd
    - publication_bias.qmd
    - references.qmd

number-sections: false 
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      light: litera
      dark: darkly
    mainfont: "Atkinson Hyperlegible"
    code-tools: true
    toc: true
    toc-depth: 3
    toc-location: left
    code-copy: true

execute:
  freeze: auto # Automatically caches results to speed up rendering
  warning: false
  message: false

editor: visual

