project:
  type: book
  output-dir: ../docs
  resources:
    - styles.css
    - images

book:
  title: "Music exposure reduces anxiety- and depression-like behavior in rodents: a systematic review and multilevel meta-analysis"
  subtitle: "Online supplementary (reproducible workflow + full outputs)"
  author:
    - name: Santiago Ortega
      attributes:
        corresponding: true
    - name: Anna Lenz
    - name: Erick Lundgren
    - name: Ayumi Mizuno
    - name: Sergio Poo Hernandez
    - name: Shinichi Nakagawa
    - name: Malgorzata Lagisz
  date: last-modified

  # Adds top bar + links
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/Santiago-0rtega/Music_on_anxiety_depression_meta_analysis  # change
        aria-label: GitHub
      - text: "OSF"
        href: https://osf.io/mv78t                   # change if needed
      - text: "Paper"
        href: https://doi.org/XXXXX                  # optional

  # Adds left sidebar controls + search box
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2

  chapters:
    - index.qmd
    - effect_size_calculation.qmd
    - overall_effect.qmd
    - uni_moderators.qmd
    - publication_bias.qmd
    - leave_one_out.qmd
    - main_figures.qmd
    - Alluvial.qmd


number-sections: false
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      light: litera 
      dark: darkly
    css: styles.css
    mainfont: "Atkinson Hyperlegible"
    fontsize: 1.05em
    linestretch: 1.35
    favicon: images/favicon.png

    toc: true
    toc-depth: 3
    toc-location: left

    code-tools: true
    code-copy: true
    

    link-external-newwindow: true
    smooth-scroll: true

    # nicer citations in browser
    citeproc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1400px  
      margin-width: 200px
      gutter-width: 1.5rem
execute:
  freeze: auto
  warning: false
  message: false

editor: visual
