project:
  type: book
  output-dir: ../docs

book:
  title: "Music_meta_book"
  author: "TBA"
  date: last-modified
  chapters:
    - index.qmd
    - part: "lnRR"
      chapters:
        - lnRR.qmd
        - overall_effect.qmd
        - uni_moderators.qmd
        - multi_moderator.qmd
        - publication_bias.qmd
     - part: "lnVR"
       chapters: 
         - lnVR.qmd
    # - part: "lnCVR"
    #   chapters:
    #     - placeholder.qmd

number-sections: false 
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      light: litera
      dark: darkly
    # Note: Ensure you are importing this font in a CSS file or header
    mainfont: "Atkinson Hyperlegible" 
    code-tools: true
    toc: true
    toc-depth: 3
    toc-location: left
    code-copy: true

execute:
  freeze: auto
  warning: false
  message: false

editor: visual